name       : perl-time-hires
version    : '1.9764'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/Time-HiRes-1.9764.tar.gz : 9841be5587bfb7cd1f2fe267b5e5ac04ce25e79d5cc77e5ef9a9c5abd101d7b1
homepage   : https://metacpan.org/pod/Time::HiRes
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Time::HiRes - High resolution alarm, sleep, gettimeofday, interval timers
description: |
    Implement usleep, ualarm, and gettimeofday for Perl, as well as wrappers to implement time, sleep, and alarm that know about non-integral seconds.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
