name       : perl-time-hires
version    : '1.9754'
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/J/JH/JHI/Time-HiRes-1.9754.tar.gz : 6654c007b2d597f863a0bb2ed69c639f0d552f598e35cf474fc6e89b9225b063
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Time::HiRes - High resolution alarm, sleep, gettimeofday, interval timers
description: |
    Implement usleep, ualarm, and gettimeofday for Perl, as well as wrappers to implement time, sleep, and alarm that know about non-integral seconds.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
