name       : perl-time-hires
version    : '1.9757'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/J/JH/JHI/Time-HiRes-1.9757.tar.gz : 3cda1cf9c0eadc15bdd6d38592164891f6d44c3e264efdba790b11695adf42a4
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Time::HiRes - High resolution alarm, sleep, gettimeofday, interval timers
description: |
    Implement usleep, ualarm, and gettimeofday for Perl, as well as wrappers to implement time, sleep, and alarm that know about non-integral seconds.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
