name       : perl-time-hires
version    : '1.9760'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/A/AT/ATOOMIC/Time-HiRes-1.9760.tar.gz : 2cb898bff42bc10024e0a3252c79e13a2eb7a8a5fb3367bb60583b576a11702b
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Time::HiRes - High resolution alarm, sleep, gettimeofday, interval timers
description: |
    Implement usleep, ualarm, and gettimeofday for Perl, as well as wrappers to implement time, sleep, and alarm that know about non-integral seconds.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
