name       : perl-time-hires
version    : 1.9753
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/J/JH/JHI/Time-HiRes-1.9753.tar.gz : 0fbfd5f99cdd26011d5c0bc3a8e369dacc4a9e1d1658f4663ac6018f2cec4915
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Time::HiRes - High resolution alarm, sleep, gettimeofday, interval timers
description: |
    Implement usleep, ualarm, and gettimeofday for Perl, as well as wrappers to implement time, sleep, and alarm that know about non-integral seconds.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
